Support version 3 of Sendy API
kloarubeek/SendyClient.Net pull request #9
Opened 2018-09-19 19:50 UTC by mguinness

See https://github.com/kloarubeek/SendyClient.Net/issues/8 for more details.

2018-09-20 02:43 UTC, mguinness commented
Is there any way to find out what code needs to be refactored?  I'm not willing to submit additional permissions that the Better Code Hub is requesting (see below).

![image](https://user-images.githubusercontent.com/14002844/45792762-128f9d80-bc44-11e8-80dd-139c8990fce7.png)

2018-09-20 06:45 UTC, kloarubeek requested changes
Thanks for the changes, looks good! If you change the minor changes I suggest, I can merge it and see what BetterCodeHub has to say.

2018-09-20 06:45 UTC, kloarubeek commented on src/Sendy.Client.csproj
> +    <Version>2.3.0</Version>
Please update it to 3.0.0 as it has breaking changes (by adding Async to all methods).

2018-09-20 06:45 UTC, kloarubeek commented on README.md
> +The `SendyClient` class constructor now includes a new parameter named apiVer where you can pass in the version of Sendy you're working against.
Good that you updated the readme with this 👏 
It's worth to mention why you need to pass on this version (to enable v3 functionality).

2018-09-20 06:45 UTC, kloarubeek commented on src/SendyClient.cs
> +        private readonly Version _apiVer;
I see we're mixing tabs and spaces (sorry for the initial tab setup). Can you easily change your changes to use tabs? Or update everything to use spaces.

2018-09-20 06:55 UTC, kloarubeek commented
BetterCodeHub is complaining about this:

CreateCampaign and Subscribe are getting too big with too many parameters. You could fix this by creating a new model that holds all the parameters and moving some code from CreateCampaign to a private method.

![image](https://user-images.githubusercontent.com/20110699/45800946-bc0d7800-bcb2-11e8-9586-4ed7e1f50c45.png)

2018-09-25 03:32 UTC, mguinness commented
@kloarubeek Thanks for the feedback, I've been busy so I haven't gotten around to this yet.

2018-10-18 23:46 UTC, mguinness commented
@kloarubeek Made changes as requested, let me know if any additional changes are needed.

2018-10-20 19:48 UTC, kloarubeek approved these changes

2018-10-20 19:50 UTC, merged

2018-10-20 19:51 UTC, kloarubeek commented
Thanks for your help! I'll submit a brand new v3 to NuGet :+1:

2018-10-20 22:51 UTC, mguinness commented
@kloarubeek Thanks Jereon!